const StatusMessage = {
  SUCCESS: "SUCCESS",
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  TOKEN_NOT_VALID:"TOKEN_NOT_VALID",
  UNAUTHORIZED: "UNAUTHORIZED",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  NO_CONTENT: "NO CONTENT",
  PLAYLIST_NOT_FOUND: "PLAYLIST NOT FOUND",
  SONG_ADDED_TO_PLAYLIST: "SONG ADDED TO PLAYLIST",
  SONG_ALREADY_EXIST: "SONG ALREADY EXIST",
  SONG_NOT_FOUND_IN_PLAYLIST: "SONG NOT FOUND IN PLAYLIST",
  SONG_REMOVED_FROM_PLAYLIST:"SONG REMOVED FROM PLAYLIST"
};

module.exports = { StatusMessage };
